### ISSUE TITLE
coseq main function error

### ISSUE THREAD

**Issue by na396** [andreamrau/coseq#5]
Greeting, 
I have the following error on coseq function.
unable to find an inherited method for function ‘coseq’ for signature ‘"missing"’

the main call is 
coseq(counts = exp, K = 2:40, model = "kmeans", 
              transformation = "logclr", seed = 123)
where counts is an expression matrix, row: genes, columns: samples.

Thank you in advance

**Comment by andreamrau** [comment]
Hi, thanks for your question. What is `class(exp)`, the class of your expression count data? Could you send a reproducible example and information about your R/coseq versions?
